spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://keycloak:8080/realms/tpi-realm/protocol/openid-connect/certs}
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: orders-service
          uri: ${TPI_ORDERS_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/ordenes/**
          filters:
            - RewritePath=/api/ordenes(?<segment>/?.*), /api/v1/solicitudes${segment}

        - id: fleet-service
          uri: ${TPI_FLEET_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/fleet/**
          filters:
            - RewritePath=/api/fleet(?<segment>/?.*), /api/v1${segment}

        - id: locations-service
          uri: ${TPI_LOCATIONS_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/locations/**
          filters:
            - RewritePath=/api/locations(?<segment>/?.*), /api/v1${segment}

        - id: pricing-service
          uri: ${TPI_PRICING_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/pricing/**
          filters:
            - RewritePath=/api/pricing(?<segment>/?.*), /api/v1${segment}
