spring:
  application:
    name: pricing-service
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
pricing:
  combustible:
    costo-litro: ${PRICING_COMBUSTIBLE_COSTO_LITRO:1.0}
